//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoToo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCENTE()
        {
            this.RESERVA = new HashSet<RESERVA>();
            this.SOLICITUD_RESERVA = new HashSet<SOLICITUD_RESERVA>();
        }
    
        public string DUI { get; set; }
        public string NOMBRE_DOCENTE { get; set; }
        public string APELLIDO_DOCENTE { get; set; }
        public string NIT { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string ESTADO_ACTIVIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_RESERVA> SOLICITUD_RESERVA { get; set; }
    }
}
