//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoToo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyecto2Entities : DbContext
    {
        public proyecto2Entities()
            : base("name=proyecto2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASIGNATURA> ASIGNATURA { get; set; }
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<CATALOGO> CATALOGO { get; set; }
        public virtual DbSet<DOCENTE> DOCENTE { get; set; }
        public virtual DbSet<ESCUELA> ESCUELA { get; set; }
        public virtual DbSet<GALERIA> GALERIA { get; set; }
        public virtual DbSet<HORARIO> HORARIO { get; set; }
        public virtual DbSet<LOCAL> LOCAL { get; set; }
        public virtual DbSet<PERMISO> PERMISO { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<ROLE_USUARIO> ROLE_USUARIO { get; set; }
        public virtual DbSet<SOLICITUD_RESERVA> SOLICITUD_RESERVA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
