//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoToo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO
    {
        public int ID_PERMISO { get; set; }
        public string NAME_PERMISO { get; set; }
        public string SLUG_PERMISO { get; set; }
        public string DESCRIPCION_PERMISO { get; set; }
    }
}
