//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoToo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public string CODIGO_DE_RESERVA { get; set; }
        public string DUI { get; set; }
        public System.DateTime FECHA_ACEPTADA { get; set; }
    
        public virtual DOCENTE DOCENTE { get; set; }
    }
}
