//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoToo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_USUARIO
    {
        public int ROL_ID { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
