//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoToo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_RESERVA
    {
        public int ID_SOLUCITUD { get; set; }
        public string DUI { get; set; }
        public string CODIGO_LOCAL { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<bool> APROBADO { get; set; }
    
        public virtual DOCENTE DOCENTE { get; set; }
        public virtual LOCAL LOCAL { get; set; }
    }
}
